CODE/WebProject1/Controllers/jailersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProject1.DAL;
using WebProject1.Models;

namespace WebProject1.Controllers
{
    [myAuthorize]
    [jailerAuthentication]
    public class jailersController : Controller
    {
        private prisonerManagementSystemEntities db = new prisonerManagementSystemEntities();
        dynamic obj = new ExpandoObject();
        

        // GET: jailers
        public ActionResult Index()
        {
            return View(db.jailer.ToList());
        }

        // GET: jailers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jailer jailer = db.jailer.Find(id);
            if (jailer == null)
            {
                return HttpNotFound();
            }
            return View(jailer);
        }

        // GET: jailers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: jailers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,cnic,contact,address,dob,image,appointment_date,retirement_date,in_service,email,password")] jailer jailer)
        {
            if (ModelState.IsValid)
            {
                db.jailer.Add(jailer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(jailer);
        }

        // GET: jailers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jailer jailer = db.jailer.Find(id);
            if (jailer == null)
            {
                return HttpNotFound();
            }
            return View(jailer);
        }

        // POST: jailers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,cnic,contact,address,dob,image,appointment_date,retirement_date,in_service,email,password")] jailer jailer)
        {
            
            if (ModelState.IsValid)
            {
                var officer = db.jailer.SingleOrDefault(f => f.id == jailer.id);
                officer.name = jailer.name;
                officer.cnic = jailer.cnic;
                officer.contact = jailer.contact;
                officer.address = jailer.address;
                officer.dob = jailer.dob;
                officer.image = jailer.image;
                officer.email = jailer.email;

                db.Entry(officer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = officer.id });
            }
            return View(jailer);
        }

        // GET: jailers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jailer jailer = db.jailer.Find(id);
            if (jailer == null)
            {
                return HttpNotFound();
            }
            return View(jailer);
        }

        // POST: jailers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            jailer jailer = db.jailer.Find(id);
            db.jailer.Remove(jailer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: jailers/Home
        public ActionResult Home()
        {
            List<prisoner_transfer_request> prisoner_transfer_requests = (from requests in db.prisoner_transfer_request
                                                                          where requests.status == "Pending"
                                                                          select requests).ToList();
            
            return View(prisoner_transfer_requests);
        }

        
        public ActionResult AllRequests()
        {
            List<prisoner_transfer_request> prisoner_transfer_requests = (from requests in db.prisoner_transfer_request
                                                                          select requests).ToList();
            
            return View(prisoner_transfer_requests);
        }

        public ActionResult SearchRequest(string searchText, string options)
        {

            if (options == "byFromJail" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.from_jail.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else if (options == "byToJail" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.to_jail.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else if (options == "byStatus" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.status.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else
            {
                return RedirectToAction("NotFound");
            }

        }

        public ActionResult NotFound()
        {
            return View();
        }


        public ActionResult ChangePassword(int id)
        {

            jailer jailer = db.jailer.Find(id);
            if (jailer == null)
            {
                return HttpNotFound();
            }
            return View(jailer);
        }

        public ActionResult ConfirmChangePassword(int id, string oldpassword, string newpassword, string newpassword1)
        {

            jailer jailer = db.jailer.Find(id);

            if (jailer == null)
            {
                return HttpNotFound();
            }

            if (jailer.password != oldpassword)
            {
                Session["passwordMessage"] = "Incorrect Old Password";
                return RedirectToAction("ChangePassword", new { id = jailer.id });
            }

            else if (newpassword != newpassword1)
            {
                Session["passwordMessage"] = "New Password did not match";
                return RedirectToAction("ChangePassword", new { id = jailer.id });
            }
            else
            {
                jailer.password = newpassword;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = jailer.id });
            }

        }
    }
}

CODE/WebProject1/Controllers/prisoner_transfer_requestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProject1.DAL;
using WebProject1.Models;

namespace WebProject1.Controllers
{
    [myAuthorize]
    public class prisoner_transfer_requestController : Controller
    {
        private prisonerManagementSystemEntities db = new prisonerManagementSystemEntities();

        // GET: prisoner_transfer_request
        public ActionResult Index()
        {
            var prisoner_transfer_request = db.prisoner_transfer_request.Include(p => p.court_officer).Include(p => p.jailer).Include(p => p.prisoner);
            return View(prisoner_transfer_request.ToList());
        }

        // GET: prisoner_transfer_request/Details/5
        [jailerAuthentication]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            prisoner_transfer_request prisoner_transfer_request = db.prisoner_transfer_request.Find(id);
            if (prisoner_transfer_request == null)
            {
                return HttpNotFound();
            }
            return View(prisoner_transfer_request);
        }

        // GET: prisoner_transfer_request/Create

        [courtOfficerAuthentication]
        public ActionResult Create()
        {
            ViewBag.court_officer_id = new SelectList(db.court_officer, "id", "name");
            ViewBag.jailer_id = new SelectList(db.jailer, "id", "name");
            ViewBag.prisonerid = new SelectList(db.prisoner, "id", "name");
            return View();
        }

        // POST: prisoner_transfer_request/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [courtOfficerAuthentication]
        public ActionResult Create([Bind(Include = "id,from_jail,to_jail,reason_of_transfer,description,request_date,accept_date,status,prisonerid,court_officer_id,jailer_id")] prisoner_transfer_request prisoner_transfer_request)
        {
            if (ModelState.IsValid)
            {
                prisoner_transfer_request.status = "Pending";
                db.prisoner_transfer_request.Add(prisoner_transfer_request);
                db.SaveChanges();
                return RedirectToAction("Home", "court_officer");
            }

            ViewBag.court_officer_id = new SelectList(db.court_officer, "id", "name", prisoner_transfer_request.court_officer_id);
            ViewBag.jailer_id = new SelectList(db.jailer, "id", "name", prisoner_transfer_request.jailer_id);
            ViewBag.prisonerid = new SelectList(db.prisoner, "id", "name", prisoner_transfer_request.prisonerid);
            return View(prisoner_transfer_request);
        }

        // GET: prisoner_transfer_request/Edit/5

        [courtOfficerAuthentication]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            prisoner_transfer_request prisoner_transfer_request = db.prisoner_transfer_request.Find(id);
            if (prisoner_transfer_request == null)
            {
                return HttpNotFound();
            }
            ViewBag.court_officer_id = new SelectList(db.court_officer, "id", "name", prisoner_transfer_request.court_officer_id);
            ViewBag.jailer_id = new SelectList(db.jailer, "id", "name", prisoner_transfer_request.jailer_id);
            ViewBag.prisonerid = new SelectList(db.prisoner, "id", "name", prisoner_transfer_request.prisonerid);
            return View(prisoner_transfer_request);
        }

        // POST: prisoner_transfer_request/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [courtOfficerAuthentication]
        public ActionResult Edit([Bind(Include = "id,from_jail,to_jail,reason_of_transfer,description,request_date,accept_date,status,prisonerid,court_officer_id,jailer_id")] prisoner_transfer_request prisoner_transfer_request)
        {
            if (ModelState.IsValid)
            {
                prisoner_transfer_request.status = "Pending";
                db.Entry(prisoner_transfer_request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Home", "court_officer");
            }
            ViewBag.court_officer_id = new SelectList(db.court_officer, "id", "name", prisoner_transfer_request.court_officer_id);
            ViewBag.jailer_id = new SelectList(db.jailer, "id", "name", prisoner_transfer_request.jailer_id);
            ViewBag.prisonerid = new SelectList(db.prisoner, "id", "name", prisoner_transfer_request.prisonerid);
            return View(prisoner_transfer_request);
        }

        // GET: prisoner_transfer_request/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            prisoner_transfer_request prisoner_transfer_request = db.prisoner_transfer_request.Find(id);
            if (prisoner_transfer_request == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Home", "court_officer");
        }

        // POST: prisoner_transfer_request/Delete/5
        
        public ActionResult DeleteConfirmed(int id)
        {
            prisoner_transfer_request prisoner_transfer_request = db.prisoner_transfer_request.Find(id);
            db.prisoner_transfer_request.Remove(prisoner_transfer_request);
            db.SaveChanges();
            return RedirectToAction("Home", "court_officer");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        public ActionResult Accept(int? id)
        {
            var request = db.prisoner_transfer_request.SingleOrDefault(f => f.id == id);
            request.status = "Accepted";
            request.accept_date = DateTime.Now.ToString("dd-MM-yyyy");
            db.SaveChanges();
            return RedirectToAction("Home", "jailers");
        }

        public ActionResult Reject(int? id)
        {
            var request = db.prisoner_transfer_request.SingleOrDefault(f => f.id == id);
            request.status = "Rejected";
            request.accept_date = DateTime.Now.ToString("dd-MM-yyyy");
            db.SaveChanges();
            return RedirectToAction("Home", "jailers");
        }
    }
}

CODE/WebProject1/Views/jailers/AllRequests.cshtml
@model IEnumerable<WebProject1.DAL.prisoner_transfer_request>

@using WebProject1.DAL;
@using WebProject1;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];
}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jailers/Home">
                            Home
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default" href="../../jailers/Home">
                            Pending Prisoner Transfer Requests
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default" href="../../jailers/AllRequests">
                            All Prisoner Transfer Requests
                        </a>
                    </li>


                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">
                    <li class="btn"><a href="../../jailers/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../jailers/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byFromJail" value="byFromJail">From Jail</option>
                    <option name="byToJail" value="byToJail">To Jail</option>
                    <option name="byStatus" value="byStatus">By Status</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for transfer requests">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->



<div class="slider movie-items">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="heading">All Prisoner Transfer Requests</h2>
            </div>
        </div>
        <div class="row">


            <div class="col-lg-12">

                <table class="table mytable">
                    <thead>
                        <tr>
                            <th>From Jail</th>
                            <th>To Jail</th>
                            <th>Request Date</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.from_jail
                                </td>
                                <td>
                                    @item.to_jail
                                </td>

                                <td>
                                    @item.request_date
                                </td>
                                <td>
                                    @item.status
                                </td>
                                <td>
                                    <button class="mybutton" onclick="window.location.href = '@Url.Action("Details", "prisoner_transfer_request", new {id = item.id})';">Details</button>

                                    </td>

                            </tr>
                        }




                    </tbody>
                </table>
            </div>


        </div>
    </div>


</div>

CODE/WebProject1/Views/jailers/Home.cshtml
@model IEnumerable<WebProject1.DAL.prisoner_transfer_request>

@using WebProject1.DAL;
@using WebProject1;
@*@model dynamic*@

@{
    ViewBag.Title = "Jailer Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];
}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="#">
                            Home
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default" href="#">
                            Pending Prisoner Transfer Requests
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default" href="../../jailers/AllRequests">
                            All Prisoner Transfer Requests
                        </a>
                    </li>


                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">
                    <li class="btn"><a href="../../jailers/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../jailers/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byFromJail" value="byFromJail">From Jail</option>
                    <option name="byToJail" value="byToJail">To Jail</option>
                    <option name="byStatus" value="byStatus">By Status</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for transfer requests">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->



<div class="slider movie-items">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="heading">Pending Prisoner Transfer Requests</h2>
            </div>
        </div>
        <div class="row">


            <div class="col-lg-12">

                <table class="table mytable">
                    <thead>
                        <tr>
                            <th>From Jail</th>
                            <th>To Jail</th>
                            <th>Request Date</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @item.from_jail
                            </td>
                            <td>
                                @item.to_jail
                            </td>

                            <td>
                                @item.request_date
                            </td>
                            <td>
                                @item.status
                            </td>
                            <td>
                                <button class="mybutton" onclick="window.location.href = '@Url.Action("Details", "prisoner_transfer_request", new {id = item.id})';">Details</button>

                                @*@Html.ActionLink("Details", "Details", "prisoner_transfer_request", new { id = item.id }, new { @class = "mybutton mybutton:hover" })*@
                            </td>

                        </tr>
                        }
                        
                            
                       

                </tbody>
            </table>
        </div>


    </div>
</div>


</div>

CODE/WebProject1/Views/jailers/SearchRequest.cshtml
@model IEnumerable<WebProject1.DAL.prisoner_transfer_request>

@using WebProject1.DAL;
@using WebProject1;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];
}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jailers/Home">
                            Home
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default" href="../../jailers/Home">
                            Pending Prisoner Transfer Requests
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default" href="../../jailers/AllRequests">
                            All Prisoner Transfer Requests
                        </a>
                    </li>


                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">
                    <li class="btn"><a href="../../jailers/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../jailers/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byFromJail" value="byFromJail">From Jail</option>
                    <option name="byToJail" value="byToJail">To Jail</option>
                    <option name="byStatus" value="byStatus">By Status</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for transfer requests">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->



<div class="slider movie-items">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="heading">Search Results</h2>
            </div>
        </div>
        <div class="row">


            <div class="col-lg-12">

                <table class="table mytable">
                    <thead>
                        <tr>
                            <th>From Jail</th>
                            <th>To Jail</th>
                            <th>Request Date</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.from_jail
                                </td>
                                <td>
                                    @item.to_jail
                                </td>

                                <td>
                                    @item.request_date
                                </td>
                                <td>
                                    @item.status
                                </td>
                                <td>
                                    <button class="mybutton" onclick="window.location.href = '@Url.Action("Details", "prisoner_transfer_request", new {id = item.id})';">Details</button>

                                    @*@Html.ActionLink("Details", "Details", "prisoner_transfer_request", new { id = item.id }, new { @class = "mybutton mybutton:hover" })*@
                                </td>

                            </tr>
                        }




                    </tbody>
                </table>
            </div>


        </div>
    </div>


</div>