CODE/WebProject1/Controllers/court_officerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProject1.DAL;
using WebProject1.Models;

namespace WebProject1.Controllers
{
    [myAuthorize]
    [courtOfficerAuthentication]
    public class court_officerController : Controller
    {
        private prisonerManagementSystemEntities db = new prisonerManagementSystemEntities();

        // GET: court_officer
        
        public ActionResult Index()
        {
            return View(db.court_officer.ToList());
        }

        // GET: court_officer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            court_officer court_officer = db.court_officer.Find(id);
            if (court_officer == null)
            {
                return HttpNotFound();
            }
            return View(court_officer);
        }

        // GET: court_officer/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: court_officer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,cnic,contact,address,dob,image,appointment_date,retirement_date,in_service,email,password")] court_officer court_officer)
        {
            if (ModelState.IsValid)
            {
                db.court_officer.Add(court_officer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(court_officer);
        }

        // GET: court_officer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            court_officer court_officer = db.court_officer.Find(id);
            if (court_officer == null)
            {
                return HttpNotFound();
            }
            return View(court_officer);
        }

        // POST: court_officer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,cnic,contact,address,dob,image,email")] court_officer court_officer)
        {
            if (ModelState.IsValid)
            {
                var officer = db.court_officer.SingleOrDefault(f => f.id == court_officer.id);
                officer.name = court_officer.name;
                officer.cnic = court_officer.cnic;
                officer.contact = court_officer.contact;
                officer.address = court_officer.address;
                officer.dob = court_officer.dob;
                officer.image = court_officer.image;
                officer.email = court_officer.email;

                db.Entry(officer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new {id = officer.id });
            }
            return View(court_officer);
        }

        // GET: court_officer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            court_officer court_officer = db.court_officer.Find(id);
            if (court_officer == null)
            {
                return HttpNotFound();
            }
            return View(court_officer);
        }

        // POST: court_officer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            court_officer court_officer = db.court_officer.Find(id);
            db.court_officer.Remove(court_officer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        // GET: court_officer/Home

        public ActionResult Home()
        {
            List<prisoner_transfer_request> prisoner_transfer_requests = (from requests in db.prisoner_transfer_request
                                                                          where requests.status == "Pending" || requests.status == "Rejected"
                                                                          select requests).ToList();

            return View(prisoner_transfer_requests);
        }

        public ActionResult AcceptedTransferRequests()
        {
            List<prisoner_transfer_request> prisoner_transfer_requests = (from requests in db.prisoner_transfer_request
                                                                          where requests.status == "Accepted"
                                                                          select requests).ToList();

            return View(prisoner_transfer_requests);
        }

        public ActionResult SearchRequest(string searchText, string options)
        {

            if (options == "byFromJail" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.from_jail.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else if (options == "byToJail" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.to_jail.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else if (options == "byRequestStatus" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.status.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else if (options == "byComplaintStatus" && searchText != "")
            {
                
                return RedirectToAction("SearchComplaints", new { searchText = searchText});
            }

            else
            {
                return RedirectToAction("NotFound");
            }

        }

        public ActionResult SearchComplaints(String searchText)
        {
            var requests = db.complaint.Where(x => x.status.Contains(searchText) || searchText == null).ToList();
            return View(requests);
        }

        public ActionResult NotFound()
        {
            return View();
        }

        public ActionResult RequestDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            prisoner_transfer_request prisoner_transfer_request = db.prisoner_transfer_request.Find(id);
            if (prisoner_transfer_request == null)
            {
                return HttpNotFound();
            }
            return View(prisoner_transfer_request);
        }

        public ActionResult AddComplaint()
        {
            
            return View();
        }

        public ActionResult ChangePassword(int id)
        {

            court_officer court_officer = db.court_officer.Find(id);
            if (court_officer == null)
            {
                return HttpNotFound();
            }
            return View(court_officer);
        }

        public ActionResult ConfirmChangePassword(int id, string oldpassword, string newpassword, string newpassword1)
        {

            court_officer court_officer = db.court_officer.Find(id);

            if (court_officer == null)
            {
                return HttpNotFound();
            }

            if(court_officer.password != oldpassword)
            {
                Session["passwordMessage"] = "Incorrect Old Password";
                return RedirectToAction("ChangePassword", new {id = court_officer.id });
            }
            
            else if (newpassword != newpassword1)
            {
                Session["passwordMessage"] = "New Password did not match";
                return RedirectToAction("ChangePassword", new { id = court_officer.id });
            }
            else
            {
                court_officer.password = newpassword;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = court_officer.id});
            }
            
        }

    }
}

CODE/WebProject1/Controllers/jailersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProject1.DAL;
using WebProject1.Models;

namespace WebProject1.Controllers
{
    [myAuthorize]
    [jailerAuthentication]
    public class jailersController : Controller
    {
        private prisonerManagementSystemEntities db = new prisonerManagementSystemEntities();
        dynamic obj = new ExpandoObject();
        

        // GET: jailers
        public ActionResult Index()
        {
            return View(db.jailer.ToList());
        }

        // GET: jailers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jailer jailer = db.jailer.Find(id);
            if (jailer == null)
            {
                return HttpNotFound();
            }
            return View(jailer);
        }

        // GET: jailers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: jailers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,cnic,contact,address,dob,image,appointment_date,retirement_date,in_service,email,password")] jailer jailer)
        {
            if (ModelState.IsValid)
            {
                db.jailer.Add(jailer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(jailer);
        }

        // GET: jailers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jailer jailer = db.jailer.Find(id);
            if (jailer == null)
            {
                return HttpNotFound();
            }
            return View(jailer);
        }

        // POST: jailers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,cnic,contact,address,dob,image,appointment_date,retirement_date,in_service,email,password")] jailer jailer)
        {
            
            if (ModelState.IsValid)
            {
                var officer = db.jailer.SingleOrDefault(f => f.id == jailer.id);
                officer.name = jailer.name;
                officer.cnic = jailer.cnic;
                officer.contact = jailer.contact;
                officer.address = jailer.address;
                officer.dob = jailer.dob;
                officer.image = jailer.image;
                officer.email = jailer.email;

                db.Entry(officer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = officer.id });
            }
            return View(jailer);
        }

        // GET: jailers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jailer jailer = db.jailer.Find(id);
            if (jailer == null)
            {
                return HttpNotFound();
            }
            return View(jailer);
        }

        // POST: jailers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            jailer jailer = db.jailer.Find(id);
            db.jailer.Remove(jailer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: jailers/Home
        public ActionResult Home()
        {
            List<prisoner_transfer_request> prisoner_transfer_requests = (from requests in db.prisoner_transfer_request
                                                                          where requests.status == "Pending"
                                                                          select requests).ToList();
            
            return View(prisoner_transfer_requests);
        }

        
        public ActionResult AllRequests()
        {
            List<prisoner_transfer_request> prisoner_transfer_requests = (from requests in db.prisoner_transfer_request
                                                                          select requests).ToList();
            
            return View(prisoner_transfer_requests);
        }

        public ActionResult SearchRequest(string searchText, string options)
        {

            if (options == "byFromJail" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.from_jail.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else if (options == "byToJail" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.to_jail.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else if (options == "byStatus" && searchText != "")
            {
                var requests = db.prisoner_transfer_request.Where(x => x.status.Contains(searchText) || searchText == null).ToList();
                return View(requests);
            }
            else
            {
                return RedirectToAction("NotFound");
            }

        }

        public ActionResult NotFound()
        {
            return View();
        }


        public ActionResult ChangePassword(int id)
        {

            jailer jailer = db.jailer.Find(id);
            if (jailer == null)
            {
                return HttpNotFound();
            }
            return View(jailer);
        }

        public ActionResult ConfirmChangePassword(int id, string oldpassword, string newpassword, string newpassword1)
        {

            jailer jailer = db.jailer.Find(id);

            if (jailer == null)
            {
                return HttpNotFound();
            }

            if (jailer.password != oldpassword)
            {
                Session["passwordMessage"] = "Incorrect Old Password";
                return RedirectToAction("ChangePassword", new { id = jailer.id });
            }

            else if (newpassword != newpassword1)
            {
                Session["passwordMessage"] = "New Password did not match";
                return RedirectToAction("ChangePassword", new { id = jailer.id });
            }
            else
            {
                jailer.password = newpassword;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = jailer.id });
            }

        }
    }
}

CODE/WebProject1/Views/prisoner_transfer_request/Create.cshtml
@model WebProject1.DAL.prisoner_transfer_request
@using WebProject1.DAL;
@using WebProject1;


@{
    ViewBag.Title = "Court Officer Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];
}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../court_officer/Home">
                            Home
                        </a>
                    </li>



                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../complaints/Create">
                            Add Complaint
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../complaints/Index">
                            View Complaints
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../prisoner_transfer_request/Create">
                            Add Transfer Request
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../court_officer/AcceptedTransferRequests">
                            Accepted Transfer Requests
                        </a>
                    </li>



                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">
                    <li class="btn"><a href="../../court_officer/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../court_officer/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byFromJail" value="byFromJail">From Jail</option>
                    <option name="byToJail" value="byToJail">To Jail</option>
                    <option name="byRequestStatus" value="byRequestStatus">By Request Status</option>
                    <option name="byComplaintStatus" value="byComplaintStatus">Complaint Status</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for transfer requests and Complaints">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->


<div class="hero user-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">

                    <ul class="breadcumb">
                        <li class="active"><a href="../../court_officer/Home">Home</a></li>
                        <li> <span class="ion-ios-arrow-right"></span>Initiate Transfer Request</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-single">
    <div class="container">
        <div class="row ipad-width">
            <div class="col-md-12 col-sm-12 col-xs-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Prisoner Transfer Request</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.Label("From Jail", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.from_jail, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.from_jail, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("To Jail", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.to_jail, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.to_jail, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Reason of Transfer", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.reason_of_transfer, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.reason_of_transfer, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Request Date", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.request_date, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.request_date, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-group">
                            @Html.LabelFor(model => model.prisonerid, "Prisoner", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("prisonerid", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.prisonerid, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.court_officer_id, "Court Officer", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("court_officer_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.court_officer_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.jailer_id, "Jailer", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("jailer_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.jailer_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="mybutton" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    <button class="mybutton reject" onclick="window.location.href = '@Url.Action("Home", "court_officer")';">Back</button>
                </div>
            </div>
        </div>
    </div>
</div>

CODE/WebProject1/Views/prisoner_transfer_request/Delete.cshtml
@model WebProject1.DAL.prisoner_transfer_request

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>prisoner_transfer_request</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.from_jail)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.from_jail)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.to_jail)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.to_jail)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.reason_of_transfer)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.reason_of_transfer)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.request_date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.request_date)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.accept_date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.accept_date)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.status)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.status)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.court_officer.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.court_officer.name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.jailer.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.jailer.name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.prisoner.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.prisoner.name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

CODE/WebProject1/Views/prisoner_transfer_request/Index.cshtml
@model IEnumerable<WebProject1.DAL.prisoner_transfer_request>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.from_jail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.to_jail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.reason_of_transfer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.request_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.accept_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.court_officer.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.jailer.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.prisoner.name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.from_jail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.to_jail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reason_of_transfer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.request_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.accept_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.court_officer.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.jailer.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prisoner.name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>