CODE/WebProject1/Controllers/assetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProject1.DAL;
using WebProject1.Models;

namespace WebProject1.Controllers
{
    [myAuthorize]
    [jailOfficerAuthentication]
    public class assetsController : Controller
    {
        private prisonerManagementSystemEntities db = new prisonerManagementSystemEntities();

        // GET: assets
        public ActionResult Index()
        {
            var asset = db.asset.Include(a => a.prisoner);
            return View(asset.ToList());
        }

        // GET: assets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            asset asset = db.asset.Find(id);
            if (asset == null)
            {
                return HttpNotFound();
            }
            return View(asset);
        }

        // GET: assets/Create
        public ActionResult Create(int id)
        {
            Session["prisonerID"] = id;
            ViewBag.prisonerid = new SelectList(db.prisoner, "id", "name");
            return View();
        }

        // POST: assets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,worth,prisonerid")] asset asset)
        {
            if (ModelState.IsValid)
            {
                String prisonerid = Session["prisonerID"].ToString();
                asset.prisonerid = Int32.Parse(prisonerid);
                db.asset.Add(asset);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = asset.id });
            }

            ViewBag.prisonerid = new SelectList(db.prisoner, "id", "name", asset.prisonerid);
            return View(asset);
        }

        // GET: assets/Edit/5
        public ActionResult Edit(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            asset asset = db.asset.Find(id);
            Session["prisonerID"] = asset.prisonerid;
            if (asset == null)
            {
                return HttpNotFound();
            }
            ViewBag.prisonerid = new SelectList(db.prisoner, "id", "name", asset.prisonerid);
            return View(asset);
        }

        // POST: assets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,worth,prisonerid")] asset asset)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "prisoners", new { id = asset.prisonerid });
            }
            ViewBag.prisonerid = new SelectList(db.prisoner, "id", "name", asset.prisonerid);
            return View(asset);
        }

        // GET: assets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            asset asset = db.asset.Find(id);
            if (asset == null)
            {
                return HttpNotFound();
            }
            return View(asset);
        }

        // POST: assets/Delete/5
        
        public ActionResult DeleteConfirmed(int id)
        {
            asset asset = db.asset.Find(id);
            var prisoner_id = asset.prisonerid;
            db.asset.Remove(asset);
            db.SaveChanges();
            return RedirectToAction("Details", "prisoners", new { id = prisoner_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CODE/WebProject1/Views/assets/Create.cshtml
@model WebProject1.DAL.asset
@using WebProject1.DAL;
@using WebProject1;


@{
    ViewBag.Title = "Crime Create Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];
    var prisonerID = Session["prisonerID"];
}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/Home">
                            Home
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../prisoners/Create">
                            Add Prisoner
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/PendingComplaints">
                            Pending Complaints
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/ResolvedComplaints">
                            Resolved Complaints
                        </a>
                    </li>


                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">

                    <li class="btn"><a href="../../jail_officer/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../jail_officer/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byComplaintTitle" value="byComplaintTitle">Complaint Title</option>
                    <option name="prisonerName" value="prisonerName">Priosner</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for Prisoners and Complaints">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->
<div class="hero user-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">

                    <ul class="breadcumb">
                        <li class="active"><a href="../../jail_officer/Home">Home</a></li>
                        <li> <span class="ion-ios-arrow-right"></span>Add Asset</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-single">
    <div class="container">
        <div class="row ipad-width">
            <div class="col-md-12 col-sm-12 col-xs-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Add Asset</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.Label("Name", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @id = "name", @onChange = "checkname();", @onClick = "removetext(this, 'Asset Name');" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Worth", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.worth, new { id = "worth" })
                                @Html.ValidationMessageFor(model => model.worth, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input id="assetCreate" type="submit" value="Create" class="mybutton"/>
                            </div>
                        </div>
                    </div>
                }

                <div>
                    <button class="mybutton" onclick="window.location.href = '@Url.Action("Details", "prisoners", new {id = prisonerID})';">Back</button>
                </div>
            </div>
        </div>
    </div>
</div>

CODE/WebProject1/Views/assets/Delete.cshtml
@model WebProject1.DAL.asset

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>asset</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.worth)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.worth)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.prisoner.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.prisoner.name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

CODE/WebProject1/Views/assets/Details.cshtml
@model WebProject1.DAL.asset
@using WebProject1.DAL;
@using WebProject1;


@{
    ViewBag.Title = "Jail Officer Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];
    var prisonerID = Session["prisonerID"];
}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/Home">
                            Home
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../prisoners/Create">
                            Add Prisoner
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/PendingComplaints">
                            Pending Complaints
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/ResolvedComplaints">
                            Resolved Complaints
                        </a>
                    </li>


                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">

                    <li class="btn"><a href="../../jail_officer/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../jail_officer/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byComplaintTitle" value="byComplaintTitle">Complaint Title</option>
                    <option name="prisonerName" value="prisonerName">Priosner</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for Prisoners and Complaints">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->



<div class="slider movie-items">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="heading">Asset Details </h2>
            </div>
        </div>
        <div class="row">


            <div class="col-lg-12">

                <table class="table mytable">

                    <tbody>
                        <tr>
                            <th>Name</th>
                            <td>@Model.name</td>
                        </tr>

                        <tr>
                            <th>Worth</th>
                            <td>@Model.worth</td>
                        </tr>





                        <tr>
                            <td>
                                <button class="mybutton" onclick="window.location.href = '@Url.Action("Edit", "assets", new {id = Model.id})';">Edit</button>

                            </td>
                            <td>
                                <button class="mybutton" onclick="deleteConfirmed(event,@Model.id, 'assets');">Delete</button>

                            </td>
                            <td>
                                <button class="mybutton accept" onclick="window.location.href = '@Url.Action("Details", "prisoners", new {id = Model.prisonerid} )';">Back</button>
                            </td>

                        </tr>



                    </tbody>
                </table>
            </div>


        </div>
    </div>


</div>

CODE/WebProject1/Views/assets/Edit.cshtml
@model WebProject1.DAL.asset
@using WebProject1.DAL;
@using WebProject1;


@{
    ViewBag.Title = "Jail Officer Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];
    var prisonerID = Session["prisonerID"];

}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/Home">
                            Home
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../prisoners/Create">
                            Add Prisoner
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/PendingComplaints">
                            Pending Complaints
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/ResolvedComplaints">
                            Resolved Complaints
                        </a>
                    </li>


                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">

                    <li class="btn"><a href="../../jail_officer/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../jail_officer/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byComplaintTitle" value="byComplaintTitle">Complaint Title</option>
                    <option name="prisonerName" value="prisonerName">Priosner</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for Prisoners and Complaints">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->

<div class="hero user-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">

                    <ul class="breadcumb">
                        <li class="active"><a href="../../jail_officer/Home">Home</a></li>
                        <li> <span class="ion-ios-arrow-right"></span>Edit Asset</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-single">
    <div class="container">
        <div class="row ipad-width">
            <div class="col-md-12 col-sm-12 col-xs-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Asset</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.worth, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.worth, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.worth, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.prisonerid, "Prisoner", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("prisonerid", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.prisonerid, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="mybutton" />
                            </div>
                        </div>
                    </div>
                }

                    <div>
                        <button class="mybutton" onclick="window.location.href = '@Url.Action("Details", "prisoners", new {id = prisonerID })';">Back</button>
                    </div>
            </div>
        </div>
    </div>
</div>

CODE/WebProject1/Views/assets/Index.cshtml
@model IEnumerable<WebProject1.DAL.asset>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.worth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.prisoner.name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.worth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prisoner.name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>