CODE/WebProject1/Controllers/prisonersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProject1.DAL;
using WebProject1.Models;

namespace WebProject1.Controllers
{
    [myAuthorize]
    public class prisonersController : Controller
    {
        private prisonerManagementSystemEntities db = new prisonerManagementSystemEntities();

        // GET: prisoners
        public ActionResult Index()
        {
            return View(db.prisoner.ToList());
        }

        // GET: prisoners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            prisoner prisoner = db.prisoner.Find(id);
            if (prisoner == null)
            {
                return HttpNotFound();
            }
            return View(prisoner);
        }

        // GET: prisoners/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: prisoners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,cnic,dob,father_name,punishment,category,imprisonment_duration,cell_type,allocated_meeting_time,available_meeting_time,address,image,stipend")] prisoner prisoner)
        {
            if (ModelState.IsValid)
            {
                if(prisoner.image == null)
                {
                    prisoner.image = "default_prisoner.jpg";
                }
                prisoner.stipend = 0;
                prisoner.available_meeting_time = prisoner.allocated_meeting_time;
                db.prisoner.Add(prisoner);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = prisoner.id});
            }

            return View(prisoner);
        }

        // GET: prisoners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            prisoner prisoner = db.prisoner.Find(id);
            if (prisoner == null)
            {
                return HttpNotFound();
            }
            return View(prisoner);
        }

        // POST: prisoners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,cnic,dob,father_name,punishment,category,imprisonment_duration,cell_type,allocated_meeting_time,available_meeting_time,address,image,stipend")] prisoner prisoner)
        {
            if (ModelState.IsValid)
            {

                // stipend &  available meeting time not used, it is calculated on runtime
                prisoner.stipend = 100;
                prisoner.available_meeting_time = "100";

                db.Entry(prisoner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new {id = prisoner.id });
            }
            return View(prisoner);
        }

        // GET: prisoners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            prisoner prisoner = db.prisoner.Find(id);
            if (prisoner == null)
            {
                return HttpNotFound();
            }
            return View(prisoner);
        }

        // POST: prisoners/Delete/5
        
        public ActionResult DeleteConfirmed(int id)
        {
            prisoner prisoner = db.prisoner.Find(id);
            db.prisoner.Remove(prisoner);
            db.SaveChanges();
            return RedirectToAction("Home", "jail_officer");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CODE/WebProject1/Views/prisoners/Create.cshtml
@model WebProject1.DAL.prisoner
@using WebProject1.DAL;
@using WebProject1;


@{
    ViewBag.Title = "Jail Officer Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];

}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/Home">
                            Home
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../prisoners/Create">
                            Add Prisoner
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/PendingComplaints">
                            Pending Complaints
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/ResolvedComplaints">
                            Resolved Complaints
                        </a>
                    </li>


                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">

                    <li class="btn"><a href="../../jail_officer/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../jail_officer/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byComplaintTitle" value="byComplaintTitle">Complaint Title</option>
                    <option name="prisonerName" value="prisonerName">Priosner</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for Prisoners and Complaints">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->
<div class="hero user-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">

                    <ul class="breadcumb">
                        <li class="active"><a href="../../jail_officer/Home">Home</a></li>
                        <li> <span class="ion-ios-arrow-right"></span>Add Prisoner</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-single">
    <div class="container">
        <div class="row ipad-width">
            <div class="col-md-12 col-sm-12 col-xs-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Add Prisoner</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.Label("Name", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("CNIC", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.cnic, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.cnic, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Date of Birth", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.dob, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-group">
                            @Html.Label("Father's Name", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.father_name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.father_name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Punishmnet", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.punishment, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.punishment, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Cell Type", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.cell_type, new { htmlAttributes = new { @class = "form-control", placeholder = "1 for First Time, 2 For Regular" } })
                                @Html.ValidationMessageFor(model => model.cell_type, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Category", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.category, new { htmlAttributes = new { @class = "form-control", placeholder = "1 for First Time, 2 For Regular" } })
                                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Imprisonment Duration", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.imprisonment_duration, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.imprisonment_duration, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-group">
                            @Html.Label("Allocated Meeting Time", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.allocated_meeting_time, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter in Minutes" } })
                                @Html.ValidationMessageFor(model => model.allocated_meeting_time, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-group">
                            @Html.Label("Address", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Image url", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Add Prisoner" class="mybutton" />
                            </div>
                        </div>
                    </div>
                }


                <div>
                    <button class="mybutton" onclick="window.location.href = '@Url.Action("Home", "jail_officer")';">Back</button>
                </div>
            </div>
        </div>
    </div>
</div>

CODE/WebProject1/Views/prisoners/Delete.cshtml
@model WebProject1.DAL.prisoner

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>prisoner</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.cnic)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.cnic)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.dob)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.dob)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.father_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.father_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.punishment)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.punishment)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.category)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.category)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.imprisonment_duration)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.imprisonment_duration)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.cell_type)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.cell_type)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.allocated_meeting_time)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.allocated_meeting_time)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.available_meeting_time)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.available_meeting_time)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.image)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.image)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.stipend)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.stipend)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

CODE/WebProject1/Views/prisoners/Edit.cshtml
@model WebProject1.DAL.prisoner
@using WebProject1.DAL;
@using WebProject1;

@{
    ViewBag.Title = "Jail Officer Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userID = Session["userid"];

}


<!-- BEGIN | Header -->
<header class="ht-header">
    <div class="container">
        <nav class="navbar navbar-default navbar-custom">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <div id="nav-icon1">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <a href="#"><img class="logo" src="~/Images/logo1.png" alt="" width="119" height="58"><div><h4></h4></div></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav flex-child-menu menu-left">
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/Home">
                            Home
                        </a>
                    </li>

                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../prisoners/Create">
                            Add Prisoner
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/PendingComplaints">
                            Pending Complaints
                        </a>
                    </li>
                    <li class="dropdown first">
                        <a class="btn btn-default " href="../../jail_officer/ResolvedComplaints">
                            Resolved Complaints
                        </a>
                    </li>


                </ul>
                <ul class="nav navbar-nav flex-child-menu menu-right">

                    <li class="btn"><a href="../../jail_officer/Details/@userID">Settings</a></li>
                    <li class="btn"><a href="../../Home/Login">Log Out</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <!-- top search form -->
        <form id="searchBar" action="../../jail_officer/SearchRequest">
            <div class="top-search">
                <select name="options">
                    <option name="byComplaintTitle" value="byComplaintTitle">Complaint Title</option>
                    <option name="prisonerName" value="prisonerName">Priosner</option>

                </select>
                <input type="text" name="searchText" placeholder="Search for Prisoners and Complaints">
                <button id="searchButton" class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
</header>
<!-- END | Header -->

<div class="hero user-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">

                    <ul class="breadcumb">
                        <li class="active"><a href="../../jail_officer/Home">Home</a></li>
                        <li> <span class="ion-ios-arrow-right"></span>Edit Prisoner Profile</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-single">
    <div class="container">
        <div class="row ipad-width">
            <div class="col-md-12 col-sm-12 col-xs-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>prisoner</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.cnic, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.cnic, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.cnic, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.dob, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.dob, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.father_name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.father_name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.father_name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.punishment, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.punishment, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.punishment, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.category, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.imprisonment_duration, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.imprisonment_duration, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.imprisonment_duration, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.cell_type, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.cell_type, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.cell_type, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.allocated_meeting_time, htmlAttributes: new { @class = "control-label col-md-2", placeholder = "Enter in Minutes" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.allocated_meeting_time, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.allocated_meeting_time, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        

                        <div class="form-group">
                            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                            </div>
                        </div>

                       

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="mybutton" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    <button class="mybutton reject" onclick="window.location.href = '@Url.Action("Details", "prisoners", new { id = Model.id})';">Back</button>

                </div>
            </div>
        </div>
    </div>
</div>